name: Test run
on: 
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Run tests
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_APP_ID: ${{ secrets.BROWSERSTACK_APP_ID }}
        run: npm run wdio:bs:galaxy:s21u
      - name: Copy History
        if: always()
        run: npm run allure:history
      - name: Generate report
        if: always()
        run: npm run allure:generate
      - name: Upload report
        uses: actions/upload-artifact@v1
        if: always()
        with: 
          name: allure-results
          path: ./allure-results
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: allure-report
          target-folder: docs
